const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const html=fs.readFileSync('css-arcade-game.html','utf8');
const css=fs.readFileSync('css-arcade-game.css','utf8');
const js=fs.readFileSync('css-arcade-game.js','utf8');
assert.doesNotThrow(()=>new vm.Script(js,{filename:'css-arcade-game.js'}));
['grid','selectors','box','divs','position','responsive'].forEach(game=>assert.ok(js.includes(game+':'),'falta juego '+game));
['Grid Forge','Selector Hunt','Box Model Lab','DIV Lab','Position Rescue','Responsive Racer'].forEach(name=>assert.ok(js.includes(name),'falta '+name));
assert.ok((js.match(/title:'/g)||[]).length >=45,'faltan niveles de arcade');
assert.ok(html.includes('id="cssEditor"'));
assert.ok(html.includes('id="targetFrame"'));
assert.ok(html.includes('id="playerFrame"'));
assert.ok(html.includes('Comprobar'));
assert.ok(js.includes('getComputedStyle'));
assert.ok(js.includes('localStorage'));
assert.ok(js.includes("e.ctrlKey&&e.key==='Enter'"));
assert.ok(js.includes('previewWidth'));
assert.ok(css.includes('.preview-grid'));
assert.ok(css.includes('.editor-panel'));
assert.ok(css.includes('body.embed-mode'));
assert.ok(css.includes('@media(max-width:760px)'));
assert.ok(js.includes('Boss · dashboard de DIVs'));
assert.ok(js.includes('place-items:center'));
assert.ok(js.includes('z-index'));
console.log({status:'ok',games:6,levels:'45+',divLevels:12,editable:true,inlinePreview:true});