(()=>{
  if(window.__gitSectionAdded)return;
  window.__gitSectionAdded=true;

  const terminal=text=>`<pre style="margin:0;padding:14px;border-radius:10px;color:#d1fae5;background:#07130f;font:14px/1.55 ui-monospace,monospace;white-space:pre-wrap">${text}</pre>`;
  const G=(command,name,description,code,result,meta={})=>T(
    command,name,description,code,terminal(result),[],{kind:meta.kind||'Git',tip:meta.tip||''}
  );

  sections.push(
    {
      title:'Git · Principiante',
      description:'Comprende el control de versiones y aprende a registrar cambios locales con seguridad.',
      quote:'“Un commit útil explica una decisión pequeña y completa.”',
      challenge:'Crea un repositorio local y registra su primer cambio.',
      items:[
        G('Git','¿Qué es el control de versiones?','Git guarda instantáneas del proyecto para consultar su evolución, comparar cambios y recuperar versiones anteriores. El repositorio contiene archivos de trabajo, un área de preparación y un historial de commits.','# Flujo básico\narchivos modificados → git add → área preparada → git commit → historial','Trabajo → Preparación → Commit',{kind:'Concepto',tip:'Git trabaja localmente; una plataforma como GitHub aloja una copia remota del repositorio.'}),
        G('git config','Configurar la identidad','Define el nombre y correo que aparecerán como autor de los commits. La opción --global aplica la identidad a todos los repositorios del usuario.','git config --global user.name "Ana Pérez"\ngit config --global user.email "ana@ejemplo.com"\ngit config --list','user.name=Ana Pérez\nuser.email=ana@ejemplo.com',{kind:'Configuración'}),
        G('git init','Crear un repositorio','Inicializa Git en la carpeta actual y crea el directorio interno .git, donde se almacena el historial. No modifica los archivos existentes.','cd mi-proyecto\ngit init','Initialized empty Git repository in mi-proyecto/.git/',{kind:'Inicio',tip:'Ejecuta git init solo en la raíz real del proyecto, no en una carpeta superior que contenga otros trabajos.'}),
        G('git status','Consultar el estado','Muestra la rama actual y clasifica archivos sin seguimiento, modificados o preparados. Es el comando más útil antes de agregar, confirmar o cambiar de rama.','git status','On branch main\nChanges not staged for commit:\n  modified: index.html',{kind:'Inspección'}),
        G('git add','Preparar cambios','Copia al área de preparación la versión actual de los archivos indicados. Permite decidir exactamente qué formará parte del próximo commit.','git add index.html estilos.css\ngit status --short','M  index.html\nA  estilos.css',{kind:'Preparación',tip:'Prefiere indicar archivos concretos cuando el proyecto contiene cambios no relacionados.'}),
        G('git diff','Revisar diferencias','Compara el contenido para saber qué líneas se añadieron o eliminaron. Sin opciones muestra cambios no preparados; --staged revisa lo que entrará al commit.','git diff\ngit diff --staged','-  <h1>Inicio</h1>\n+  <h1>Biblioteca web</h1>',{kind:'Inspección'}),
        G('git commit','Registrar una versión','Crea una instantánea con los cambios preparados. El mensaje debe resumir con claridad qué resultado aporta esa versión.','git commit -m "Mejora el encabezado principal"','[main a1b2c3d] Mejora el encabezado principal\n 2 files changed, 8 insertions(+), 2 deletions(-)',{kind:'Historial'}),
        G('git log','Consultar el historial','Presenta los commits desde el más reciente. --oneline resume cada registro y --decorate muestra referencias como ramas y etiquetas.','git log --oneline --decorate -5','a1b2c3d (HEAD -> main) Mejora el encabezado principal\n8e7f6a5 Crea la estructura inicial',{kind:'Historial'})
      ]
    },
    {
      title:'Git · Intermedio',
      description:'Trabaja con ramas y sincroniza el repositorio local con un remoto.',
      quote:'“Las ramas aíslan el trabajo; la integración vuelve a reunirlo.”',
      challenge:'Desarrolla una mejora en una rama y combínala con main.',
      items:[
        G('git clone','Clonar un repositorio','Descarga un repositorio remoto completo, configura origin y crea una carpeta de trabajo con la rama principal activa.','git clone https://github.com/equipo/proyecto.git\ncd proyecto','Cloning into \'proyecto\'...\nReceiving objects: 100%',{kind:'Remotos'}),
        G('git branch','Administrar ramas','Lista las ramas locales. Con un nombre nuevo crea una referencia independiente sin cambiar todavía hacia ella.','git branch\ngit branch mejora-menu','* main\n  mejora-menu',{kind:'Ramas'}),
        G('git switch','Cambiar o crear una rama','Cambia la rama activa. La opción -c crea la rama y se mueve a ella en un solo paso, dejando main sin modificaciones.','git switch -c mejora-menu','Switched to a new branch \'mejora-menu\'' ,{kind:'Ramas'}),
        G('git merge','Combinar ramas','Integra en la rama actual los commits de otra rama. Primero cambia a la rama que recibirá los cambios y luego ejecuta merge.','git switch main\ngit merge mejora-menu','Updating a1b2c3d..d4e5f6a\nFast-forward\n menu.css | 12 ++++++++++++',{kind:'Integración'}),
        G('git remote','Configurar un remoto','Asocia una URL con un nombre corto. origin es la convención para el remoto principal, pero no es una palabra obligatoria.','git remote add origin https://github.com/equipo/proyecto.git\ngit remote -v','origin  https://github.com/equipo/proyecto.git (fetch)\norigin  https://github.com/equipo/proyecto.git (push)',{kind:'Remotos'}),
        G('git fetch','Descargar referencias','Consulta el remoto y actualiza referencias como origin/main sin mezclar cambios en la rama local. Permite revisar antes de integrar.','git fetch origin\ngit log --oneline main..origin/main','f7a8b9c Corrige navegación móvil',{kind:'Sincronización'}),
        G('git pull','Descargar e integrar','Obtiene los cambios remotos y los integra en la rama activa. Conviene tener el trabajo confirmado o guardado y revisar primero el estado.','git status\ngit pull --ff-only origin main','Updating d4e5f6a..f7a8b9c\nFast-forward',{kind:'Sincronización',tip:'--ff-only evita crear una combinación automática cuando las ramas han divergido.'}),
        G('git push','Publicar commits','Envía commits locales al remoto. -u establece la relación de seguimiento para que los próximos push puedan ejecutarse sin indicar rama.','git push -u origin mejora-menu','branch \'mejora-menu\' set up to track \'origin/mejora-menu\'.',{kind:'Publicación',tip:'Revisa git status, el diff preparado y el nombre de la rama antes de publicar.'}),
        G('.gitignore','Ignorar archivos','El archivo .gitignore enumera patrones que Git no debe comenzar a seguir, como dependencias, secretos locales o archivos generados.','node_modules/\n.env\ndist/\n*.log','Los archivos coincidentes dejan de aparecer como “untracked”.',{kind:'Configuración',tip:'.gitignore no deja de seguir archivos que ya estaban confirmados en el historial.'})
      ]
    },
    {
      title:'Git · Historial, commits y recuperación',
      description:'Aprende a seleccionar commits concretos, inspeccionarlos, recuperar archivos, crear ramas desde versiones anteriores y elegir la estrategia correcta para deshacer cambios.',
      quote:'“El hash identifica el commit; el comando que elijas decide qué hacer con esa versión.”',
      challenge:'Busca un commit antiguo, inspecciónalo, crea una rama desde él y recupera un archivo sin modificar main.',
      items:[
        G('git log --graph','Ver el historial como un mapa','Antes de seleccionar un commit conviene visualizar ramas, merges y etiquetas. --all incluye referencias de todas las ramas locales y remotas conocidas; --graph dibuja la relación entre commits.','git log --oneline --graph --decorate --all','* d4e5f6a (HEAD -> main) Agrega buscador\n| * c3d4e5f (feature) Prueba nuevo menú\n|/\n* a1b2c3d Corrige estilos\n* 8e7f6a5 Inicio',{kind:'Historial',tip:'El texto corto como a1b2c3d es una abreviación del hash completo del commit.'}),
        G('git show','Seleccionar e inspeccionar un commit','Copia el hash que aparece en git log y pásalo a git show. Así ves autor, fecha, mensaje y diferencias de ese commit sin cambiar tu rama ni tus archivos.','git show a1b2c3d\n\n# Solo resumen\ngit show --stat a1b2c3d','commit a1b2c3d\nAuthor: Ana Pérez\n\n    Corrige estilos\n\n css/styles.css | 8 +++++---',{kind:'Inspección',tip:'Este es el primer paso recomendado cuando alguien dice “quiero seleccionar ese commit”. Primero inspecciónalo.'}),
        G('git switch --detach','Moverse temporalmente a un commit','Permite abrir el proyecto exactamente como estaba en un commit antiguo. HEAD queda separado de una rama, por eso es ideal para revisar o probar una versión, pero no para empezar trabajo permanente.','git switch --detach a1b2c3d\n\n# Volver a main\ngit switch main','HEAD is now at a1b2c3d Corrige estilos',{kind:'Historial',tip:'En detached HEAD puedes mirar y probar. Si decides trabajar desde ahí, crea una rama antes de hacer commits.'}),
        G('git switch -c <rama> <commit>','Crear una rama desde un commit antiguo','Si la versión seleccionada debe convertirse en un nuevo punto de trabajo, crea una rama directamente desde ese hash. main queda intacta.','git switch -c recuperar-diseno a1b2c3d','Switched to a new branch \'recuperar-diseno\'' ,{kind:'Ramas',tip:'Esta es una forma segura de “volver a un commit” sin borrar el historial actual.'}),
        G('git diff commit..commit','Comparar dos commits','Puedes comparar dos versiones concretas sin cambiar de rama. Git muestra qué líneas y archivos cambiaron entre ambos puntos del historial.','git diff a1b2c3d..d4e5f6a\n\n# Solo nombres de archivos\ngit diff --name-status a1b2c3d..d4e5f6a','M  index.html\nM  css/styles.css\nA  js/buscador.js',{kind:'Inspección'}),
        G('git restore --source','Recuperar un archivo desde un commit','No siempre necesitas volver todo el proyecto. --source permite tomar solo un archivo tal como estaba en un commit concreto y copiarlo al directorio de trabajo actual.','git restore --source=a1b2c3d -- css/styles.css\ngit diff -- css/styles.css','css/styles.css recupera el contenido de a1b2c3d y queda como cambio local.',{kind:'Recuperación',tip:'Después puedes revisar el diff y decidir si haces commit del archivo recuperado.'}),
        G('git cherry-pick','Traer un commit específico a la rama actual','Selecciona un commit de otra rama y aplica su cambio en la rama actual. Git crea un commit nuevo con ese contenido. Es útil cuando solo necesitas una corrección concreta y no toda la rama.','git switch main\ngit cherry-pick c3d4e5f','[main f6a7b8c] Corrige menú móvil',{kind:'Historial',tip:'Si hay conflictos, resuélvelos, ejecuta git add y después git cherry-pick --continue.'}),
        G('git branch --contains','Saber qué ramas contienen un commit','Cuando encuentras un hash y no sabes dónde quedó integrado, este comando lista las ramas que ya incluyen ese commit.','git branch --contains a1b2c3d\ngit branch -r --contains a1b2c3d','* main\n  feature/menu\n  origin/main',{kind:'Inspección'}),
        G('git commit --amend','Corregir el último commit local','Permite cambiar el mensaje o agregar archivos olvidados al commit más reciente. El commit resultante recibe un hash nuevo.','git add README.md\ngit commit --amend --no-edit\n\n# O cambiar el mensaje\ngit commit --amend -m "Documenta instalación"','[main 9f8e7d6] Documenta instalación',{kind:'Historial',tip:'Evita amend si ese commit ya fue compartido y otras personas están trabajando sobre él.'}),
        G('git reset --soft / --mixed / --hard','Mover la rama a otro commit','reset mueve la referencia de la rama. --soft conserva todos los cambios preparados; --mixed conserva archivos modificados pero vacía staging; --hard también reemplaza los archivos de trabajo.','git reset --soft HEAD~1\ngit reset --mixed HEAD~1\n\n# PELIGRO: descarta cambios locales\ngit reset --hard a1b2c3d','--soft  → commit eliminado, cambios en staging\n--mixed → commit eliminado, cambios sin stage\n--hard  → rama y archivos quedan exactamente en el commit elegido',{kind:'Recuperación',tip:'En ramas compartidas suele ser más seguro git revert. Usa --hard solo cuando entiendas qué trabajo local será descartado.'}),
        G('git reflog','Recuperar commits que parecían perdidos','reflog registra movimientos recientes de HEAD y ramas locales. Si hiciste reset, rebase o cambiaste de rama y “perdiste” un commit, normalmente puedes encontrar su hash aquí.','git reflog\n\n# Crear una rama de rescate\ngit switch -c rescate 7a6b5c4','d4e5f6a HEAD@{0}: reset: moving to HEAD~2\n7a6b5c4 HEAD@{1}: commit: trabajo importante',{kind:'Recuperación',tip:'No entres en pánico después de un reset equivocado: revisa reflog antes de seguir haciendo cambios.'}),
        G('git log -- <archivo>','Ver la historia de un archivo','Filtra el historial para conocer los commits que modificaron un archivo concreto. Con -p también puedes ver los cambios de cada commit.','git log --oneline -- css/styles.css\ngit log -p -- css/styles.css','a1b2c3d Corrige estilos del formulario\n8e7f6a5 Crea estilos iniciales',{kind:'Historial'}),
        G('git blame','Saber en qué commit cambió cada línea','Muestra el último commit que modificó cada línea de un archivo. Sirve para encontrar contexto histórico y luego inspeccionar ese hash con git show.','git blame -L 10,20 app.js','a1b2c3d (Ana 2026-09-10 10:31:00 -0500 12) fetch(url);',{kind:'Inspección',tip:'blame no debe usarse para “culpar” personas; úsalo para encontrar el contexto de una decisión.'})
      ]
    },
    {
      title:'Git · Avanzado',
      description:'Reorganiza cambios, recupera versiones, encuentra errores y resuelve integraciones de forma controlada.',
      quote:'“Antes de reescribir historial, confirma qué referencia y qué archivos serán afectados.”',
      challenge:'Resuelve un conflicto y recupera un cambio mediante una operación reversible.',
      items:[
        G('git stash','Guardar trabajo temporal','Aparta cambios sin confirmar para dejar limpia la carpeta de trabajo. list muestra las entradas y pop reaplica la más reciente eliminándola del almacén.','git stash push -m "menú en progreso"\ngit stash list\ngit stash pop','stash@{0}: On mejora-menu: menú en progreso\nDropped refs/stash@{0}',{kind:'Organización'}),
        G('git stash apply','Aplicar un stash específico','Cuando hay varias entradas no tienes que usar la última. Selecciona una por su identificador y usa apply si quieres conservarla en la lista después de restaurarla.','git stash list\ngit stash show -p stash@{1}\ngit stash apply stash@{1}','stash@{1} se aplica al directorio de trabajo y permanece guardado.',{kind:'Organización'}),
        G('git rebase','Reaplicar commits','Coloca los commits de la rama actual sobre otra base para obtener un historial lineal. Cambia identificadores, por lo que debe evitarse sobre commits compartidos.','git switch mejora-menu\ngit rebase main','Successfully rebased and updated refs/heads/mejora-menu.',{kind:'Historial',tip:'Usa rebase en trabajo local; coordina con el equipo antes de reescribir una rama publicada.'}),
        G('git rebase -i','Editar varios commits con rebase interactivo','Permite reordenar, renombrar, combinar o eliminar commits recientes. Git abre una lista donde puedes cambiar pick por reword, squash, fixup o drop.','git rebase -i HEAD~4\n\n# Ejemplo del editor\npick a1b2c3d Agrega formulario\nreword b2c3d4e Corrige texto\nsquash c3d4e5f Ajusta estilos\ndrop d4e5f6a Commit temporal','Los commits seleccionados se reescriben y reciben nuevos hashes.',{kind:'Historial',tip:'Hazlo preferiblemente antes de publicar la rama. No reescribas commits compartidos sin coordinarlo.'}),
        G('git revert','Revertir de forma segura','Crea un nuevo commit que invierte los cambios de otro. Conserva el historial y por eso es apropiado para ramas compartidas.','git revert a1b2c3d','[main e7f8a9b] Revert "Mejora el encabezado principal"',{kind:'Recuperación'}),
        G('git restore','Descartar o retirar cambios','Restaura un archivo desde el último commit. Con --staged lo retira del área de preparación sin borrar las modificaciones de la carpeta de trabajo.','git restore --staged index.html\ngit restore index.html','index.html vuelve primero a “modificado” y después recupera su versión confirmada.',{kind:'Recuperación',tip:'Antes de restaurar el archivo de trabajo, revisa git diff porque los cambios no confirmados se perderán.'}),
        G('git bisect','Encontrar el commit que introdujo un error','bisect hace una búsqueda binaria entre una versión buena y una mala. Git va seleccionando commits intermedios para que indiques si funcionan hasta encontrar el primero que introdujo el problema.','git bisect start\ngit bisect bad HEAD\ngit bisect good v1.0.0\n\n# probar la aplicación y marcar\ngit bisect good\n# o\ngit bisect bad\n\n# al terminar\ngit bisect reset','Git reduce el historial hasta identificar el primer commit defectuoso.',{kind:'Depuración',tip:'Es especialmente útil cuando sabes que una versión antigua funcionaba y la actual no.'}),
        G('conflictos','Resolver conflictos','Un conflicto aparece cuando Git no puede combinar automáticamente cambios sobre la misma zona. Edita los marcadores, conserva el resultado correcto, prepara el archivo y continúa.','git status\n# Editar <<<<<<<, ======= y >>>>>>>\ngit add index.html\ngit merge --continue','All conflicts fixed but you are still merging.\nMerge made by the recursive strategy.',{kind:'Integración'}),
        G('git tag','Etiquetar versiones','Una etiqueta nombra un commit importante, normalmente una versión publicada. Las etiquetas anotadas incluyen mensaje, autor y fecha. También puedes etiquetar un commit antiguo indicando su hash.','git tag -a v1.0.0 -m "Primera versión estable"\ngit tag -a v0.9.0 a1b2c3d -m "Versión candidata"\ngit push origin v1.0.0','* [new tag] v1.0.0 -> v1.0.0',{kind:'Versiones'})
      ]
    }
  );

  buildNav();
  render();
})();
